import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { destinations } from "../data/travelData";
import { getUser, setLoggedIn, getGuidePackages, saveGuidePackage, deleteGuidePackage, getBookings, fetchGuidePackages, removeGuidePackage, createGuidePackage, fetchBookings, getGuidePlaceAvailability, saveGuidePlaceAvailability, removeGuidePlaceAvailability, daysBetween, formatDate, rangesOverlap } from "../utils";

export default function GuideDashboard(){
 const user=getUser()||{name:"Local Guide",email:""}; const nav=useNavigate(); const [packages,setPackages]=useState([]); const [bookings,setBookings]=useState([]); const [placeAvailability,setPlaceAvailability]=useState(getGuidePlaceAvailability().filter(x=>x.guideEmail===user.email)); const [showCreate,setShowCreate]=useState(false); const [showPlace,setShowPlace]=useState(false); const [notice,setNotice]=useState("");
 const refresh=async()=>{setPackages(await fetchGuidePackages(user.email));setBookings(await fetchBookings({guideEmail:user.email}));setPlaceAvailability(getGuidePlaceAvailability().filter(x=>x.guideEmail===user.email));};
 useEffect(()=>{refresh(); const onChange=()=>refresh(); window.addEventListener("stg-data-change",onChange); const timer=setInterval(refresh,5000); window.addEventListener("focus",refresh); return()=>{window.removeEventListener("stg-data-change",onChange);window.removeEventListener("focus",refresh);clearInterval(timer)}},[]);
 const logout=()=>{setLoggedIn(false);sessionStorage.removeItem("stg_user");nav("/")};
 const activeBookings=bookings.filter(b=>b.status!=="Cancelled").length;
 return <main className="guide-page">
  <aside className="guide-sidebar"><div className="guide-brand"><div className="guide-logo"><i className="bi bi-compass"/></div><strong>Smart Travel Guide</strong><small>Guide · Share · Inspire</small></div><nav>
   <a className="active" href="#top"><i className="bi bi-house-door-fill"/>Dashboard</a><a href="#packages"><i className="bi bi-briefcase"/>My Packages</a><a href="#availability"><i className="bi bi-calendar-check"/>Place Availability</a><a href="#bookings"><i className="bi bi-clipboard-check"/>Bookings</a><a href="#profile" onClick={(e)=>{e.preventDefault();nav("/guide/profile");}}><i className="bi bi-person"/>My Profile</a>
  </nav><button className="guide-drawer-logout" onClick={logout}><i className="bi bi-box-arrow-right"/> Logout</button></aside>
  <section className="guide-main" id="top"><header className="guide-topbar"><div className="guide-welcome"><h1>Hello, {user.name?.split(" ")[0]||"Guide"}!</h1><p>Manage your packages, places and traveller bookings.</p></div><div className="guide-top-art"><img src="/assets/user-hero-clean.jpg" alt="Mountains"/><span>Local knowledge<br/>creates better journeys</span></div><button className="guide-notification"><i className="bi bi-bell-fill"/><b/></button><div className="guide-user"><div className="guide-avatar">{(user.name||"G").charAt(0)}</div><div><strong>{user.name||"Local Guide"}</strong><small>Local Guide</small></div></div></header>
   <div className="guide-content"><section className="guide-stats"><Stat icon="bi-box" value={packages.length} label="Travel Packages"/><Stat icon="bi-geo-alt" value={placeAvailability.length} label="Place Dates"/><Stat icon="bi-people-fill" value={activeBookings} label="Bookings" warm/><Stat icon="bi-star-fill" value="4.8" label="Average Rating" purple/></section>
    {notice&&<div className="alert alert-success py-2">{notice}</div>}
    <section className="guide-card guide-packages" id="packages"><div className="guide-card-heading"><div><h2>My Travel Packages</h2><p className="guide-subtitle">Packages are available to travellers after you publish them.</p></div><button className="guide-create" onClick={()=>setShowCreate(true)}><i className="bi bi-plus-lg"/>Create Package</button></div>
      {packages.length?<div className="guide-package-grid">{packages.map(p=><GuidePackage key={p.id} item={p} onDelete={()=>{removeGuidePackage(p.id);refresh();}}/>)}</div>:<Empty text="You have not created a package yet." action="Create your first package" onClick={()=>setShowCreate(true)}/>} </section>
    <section className="guide-card" id="availability"><div className="guide-card-heading"><div><h2>Place Guide Availability</h2><p className="guide-subtitle">Offer yourself as a local guide for a selected place and date.</p></div><button className="guide-create" onClick={()=>setShowPlace(true)}><i className="bi bi-plus-lg"/>Add Date</button></div>
      {placeAvailability.length?<div className="availability-list">{placeAvailability.sort((a,b)=>a.date.localeCompare(b.date)).map(x=><div className="availability-row" key={x.id}><div><strong>{x.placeName}</strong><small>{formatDate(x.date)}</small></div><span className="availability-open">Available</span><button onClick={()=>{removeGuidePlaceAvailability(x.id);refresh();}}><i className="bi bi-trash"/></button></div>)}</div>:<Empty text="No place-guide dates added yet." action="Add a place date" onClick={()=>setShowPlace(true)}/>}</section>
    <section className="guide-card bookings-card" id="bookings"><div className="guide-card-heading"><div><h2>Package Bookings</h2><p className="guide-subtitle">Every booking made by a traveller appears here.</p></div></div>{bookings.length?<div className="booking-table"><div className="booking-head"><span>Traveller</span><span>Package</span><span>Dates</span><span>Days</span><span>Status</span></div>{bookings.map(b=><div className="booking-row" key={b.id}><span className="traveller"><i className="bi bi-person-circle"/>{b.travellerName}</span><span>{b.packageName}</span><span>{formatDate(b.startDate)} – {formatDate(b.endDate)}</span><span>{b.days}</span><span><em className={b.status.toLowerCase()}>{b.status}</em></span></div>)}</div>:<Empty text="No package bookings yet."/>}</section>
   </div>
  </section>
  {showCreate&&<CreatePackageModal user={user} onClose={()=>setShowCreate(false)} onCreated={(p)=>{createGuidePackage(p).then(()=>refresh());setShowCreate(false);setNotice("Package published. Travellers can now see and book it.");setTimeout(()=>setNotice(""),3500)}}/>}
  {showPlace&&<PlaceAvailabilityModal user={user} packages={packages} onClose={()=>setShowPlace(false)} onCreated={(x)=>{saveGuidePlaceAvailability(x);refresh();setShowPlace(false);setNotice("You are now available as a local guide for that place on the selected date.");setTimeout(()=>setNotice(""),3500)}}/>}
 </main>
}
function Stat({icon,value,label,warm,purple}){return <div className={`guide-stat ${warm?"warm":""} ${purple?"purple":""}`}><i className={`bi ${icon}`}/><div><strong>{value}</strong><span>{label}</span></div></div>}
function Empty({text,action,onClick}){return <div className="empty-state guide-empty"><i className="bi bi-compass"/><strong>{text}</strong>{action&&<button onClick={onClick}>{action}</button>}</div>}
function GuidePackage({item,onDelete}){return <article className="guide-package"><div className="guide-package-image"><img src={item.image} alt={item.name}/><b>Active</b></div><div className="guide-package-body"><h3>{item.name}</h3><div className="package-meta"><span><i className="bi bi-calendar3"/>{formatDate(item.startDate)} – {formatDate(item.endDate)}</span><span><i className="bi bi-clock"/>{item.days} days</span></div><p>{item.description}</p><div className="guide-place-tags">{item.places.map(p=><span key={p.id}>{p.name}</span>)}</div><strong className="guide-price">₹ {Number(item.price).toLocaleString("en-IN")} <small>per person</small></strong><div className="package-actions"><button onClick={onDelete}>Delete</button><button onClick={()=>alert(`${item.name}\n${formatDate(item.startDate)} – ${formatDate(item.endDate)}\n${item.days} days\nPlaces: ${item.places.map(p=>p.name).join(", ")}`)}>View</button></div></div></article>}
function CreatePackageModal({user,onClose,onCreated}){const today=new Date().toLocaleDateString("en-CA");const [f,setF]=useState({name:"",startDate:"",endDate:"",price:"",description:"",image:destinations[0].image,places:[],maxTravellers:""});const set=(k,v)=>setF(x=>({...x,[k]:v})); const days=daysBetween(f.startDate,f.endDate); const toggle=p=>setF(x=>({...x,places:x.places.some(y=>y.id===p.id)?x.places.filter(y=>y.id!==p.id):[...x.places,p]})); const submit=e=>{e.preventDefault();if(!f.name||!f.startDate||!f.endDate||!f.price||!f.description||!f.places.length||days<1)return alert("Please complete the package details and select at least one place."); if(f.endDate<f.startDate)return alert("End date must be on or after start date."); onCreated({id:crypto.randomUUID(),guideEmail:user.email,guideName:user.name,name:f.name,startDate:f.startDate,endDate:f.endDate,days,price:Number(f.price),description:f.description,image:f.image,places:f.places,maxTravellers:Number(f.maxTravellers)||null,createdAt:new Date().toISOString()})}; return <Modal title="Create Travel Package" onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label="Package Name" value={f.name} onChange={v=>set("name",v)} required/><Field label="Price per Person (₹)" type="number" value={f.price} onChange={v=>set("price",v)} required/><Field label="Start Date" type="date" min={today} value={f.startDate} onChange={v=>set("startDate",v)} required/><Field label="End Date" type="date" min={f.startDate||today} value={f.endDate} onChange={v=>set("endDate",v)} required/></div><div className="calculated-days"><i className="bi bi-calendar-check"/> Number of Days: <strong>{days||"—"}</strong> <small>(calculated automatically)</small></div><div className="field"><label>Package Image</label><select value={f.image} onChange={e=>set("image",e.target.value)}>{destinations.map(d=><option value={d.image} key={d.id}>{d.name}</option>)}</select></div><div className="field"><label>Places in this Package <em>*</em></label><div className="chips">{destinations.map(p=><button type="button" key={p.id} className={f.places.some(x=>x.id===p.id)?"chip active":"chip"} onClick={()=>toggle(p)}>{p.name}</button>)}</div></div><div className="field"><label>Description <em>*</em></label><textarea rows="4" value={f.description} onChange={e=>set("description",e.target.value)} placeholder="Describe the tour, experiences and what travellers will see..."/></div><Field label="Maximum Travellers (Optional)" type="number" value={f.maxTravellers} onChange={v=>set("maxTravellers",v)}/><div className="modal-actions"><button type="button" className="btn btn-outline-primary" onClick={onClose}>Cancel</button><button className="btn btn-primary">Publish Package</button></div></form></Modal>}
function PlaceAvailabilityModal({user,packages,onClose,onCreated}){const today=new Date().toLocaleDateString("en-CA");const [placeId,setPlaceId]=useState("");const [date,setDate]=useState(""); const place=destinations.find(x=>String(x.id)===String(placeId)); const conflict=packages.some(p=>p.places?.some(x=>x.id===place?.id)&&rangesOverlap(p.startDate,p.endDate,date,date)); const submit=e=>{e.preventDefault();if(!place||!date)return alert("Select a place and date.");if(conflict)return alert("You cannot be a local guide for this place on this date because you have a package covering that date.");onCreated({id:crypto.randomUUID(),guideEmail:user.email,guideName:user.name,placeId:place.id,placeName:place.name,date})}; return <Modal title="Set Place Guide Availability" onClose={onClose}><form onSubmit={submit}><div className="field"><label>Place <em>*</em></label><select value={placeId} onChange={e=>setPlaceId(e.target.value)}><option value="">Select an available place</option>{destinations.map(d=><option value={d.id} key={d.id}>{d.name} — {d.state}</option>)}</select></div><Field label="Available Date" type="date" min={today} value={date} onChange={setDate} required/><div className={`availability-check ${conflict?"blocked":"ok"}`}>{conflict?<><i className="bi bi-x-circle"/> Not available — this date overlaps one of your packages.</>:<><i className="bi bi-check-circle"/> {date?"This date is available for place guiding.":"Select a date to check availability."}</>}</div><div className="modal-actions"><button type="button" className="btn btn-outline-primary" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={conflict}>Set Availability</button></div></form></Modal>}
function Modal({title,onClose,children}){return <div className="modal-backdrop-custom"><div className="guide-modal"><button className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</div></div>}
function Field({label,value,onChange,type="text",required,min}){return <div className="field"><label>{label} {required&&<em>*</em>}</label><input type={type} min={min} value={value} onChange={e=>onChange(e.target.value)} required={required}/></div>}
