import { destinations } from "../data/travelData";

export function getDestinationById(id) { return destinations.find(d => String(d.id) === String(id)); }
export function getSelectedDestinations() { try { const ids=JSON.parse(sessionStorage.getItem("stg_selected_places")||"[]"); return ids.map(getDestinationById).filter(Boolean); } catch { return []; } }
export function saveSelectedDestinations(ids) { sessionStorage.setItem("stg_selected_places", JSON.stringify(ids)); window.dispatchEvent(new CustomEvent("stg-selection-change")); }
export function clearSelectedDestinations() { sessionStorage.removeItem("stg_selected_places"); window.dispatchEvent(new CustomEvent("stg-selection-change")); }
export function toggleSelectedDestination(id) { const ids = JSON.parse(sessionStorage.getItem("stg_selected_places") || "[]"); const next = ids.includes(id) ? ids.filter(x => x !== id) : [...ids, id]; saveSelectedDestinations(next); return next; }
export function haversineKm(a,b){const R=6371,toRad=v=>v*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),lat1=toRad(a.lat),lat2=toRad(b.lat),x=Math.sin(dLat/2)**2+Math.sin(dLon/2)**2*Math.cos(lat1)*Math.cos(lat2);return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
export function shortestOpenRoute(points,matrix=null){const n=points.length;if(n<=1)return{order:points.map((_,i)=>i),distance:0};const dist=(i,j)=>matrix?.[i]?.[j]??haversineKm(points[i],points[j]),size=1<<n,dp=Array.from({length:size},()=>Array(n).fill(Infinity)),parent=Array.from({length:size},()=>Array(n).fill(-1));for(let i=0;i<n;i++)dp[1<<i][i]=0;for(let mask=1;mask<size;mask++)for(let last=0;last<n;last++){if(!(mask&(1<<last))||!Number.isFinite(dp[mask][last]))continue;for(let next=0;next<n;next++){if(mask&(1<<next))continue;const nm=mask|(1<<next),candidate=dp[mask][last]+dist(last,next);if(candidate<dp[nm][next]){dp[nm][next]=candidate;parent[nm][next]=last;}}}const full=size-1;let last=0;for(let i=1;i<n;i++)if(dp[full][i]<dp[full][last])last=i;const order=[];let mask=full;while(last!==-1){order.push(last);const prev=parent[mask][last];mask^=1<<last;last=prev;}order.reverse();return{order,distance:dp[full][order[order.length-1]]};}
export async function fetchRoadMatrix(points){if(points.length<2)return null;const coords=points.map(p=>`${p.lng},${p.lat}`).join(";"),url=`https://router.project-osrm.org/table/v1/driving/${coords}?annotations=distance`,r=await fetch(url);if(!r.ok)throw new Error("Routing service unavailable");const data=await r.json();if(!data.distances)throw new Error("No road distance data");return data.distances.map(row=>row.map(v=>Number.isFinite(v)?v/1000:Infinity));}
export async function fetchRoadRoute(points){if(points.length<2)return null;const coords=points.map(p=>`${p.lng},${p.lat}`).join(";"),url=`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson&steps=false`,r=await fetch(url);if(!r.ok)throw new Error("Route geometry unavailable");const data=await r.json(),route=data.routes?.[0];if(!route)throw new Error("No route found");return{distance:route.distance/1000,duration:route.duration/3600,coordinates:route.geometry.coordinates.map(([lng,lat])=>[lat,lng])};}
export function formatDistance(km){if(km<1)return`${Math.round(km*1000)} m`;return`${km.toLocaleString(undefined,{maximumFractionDigits:0})} km`;}
export function formatHours(hours){if(!Number.isFinite(hours))return"—";const totalMinutes=Math.round(hours*60),h=Math.floor(totalMinutes/60),m=totalMinutes%60;return h?`${h}h ${m?`${m}m`:""}`.trim():`${m}m`;}
